version: "3.7"

services:
  database_mongodb:
    image: mongo
    container_name: bets_database
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=teste
      - MONGO_INITDB_ROOT_PASSWORD=teste
    volumes:
      - mongodata:/data/mongo
  app:
    build: .
    container_name: bets_backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_mongodb
    depends_on:
      - database_mongodb

volumes:
  mongodata:
    driver: local