name: On Push
on: [push]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "14"

        - name: npm install
          run: npm ci

        - name: Run tests
          run: npm run test
